name: 'Warm Welcome Action'
description: 'GitHub Action to give a warm welcome on PRs'
author: 'bntz.io'
inputs:
  my_input:
    description: 'input description here'
    default: 'World'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: "blue"
  icon: "heart"
