name: "Warm Welcome Workflow"
on:
  pull_request:
  issues: 
    types: [opened]
  push:
    branches:
      - master
      - 'releases/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1.4.0
        with:
          node-version: 12.x
      - run: |
          npm i
          npm run build
          npm run pack
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - name: run gif action
      id: gif_action
      uses: ./
      with: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
    - name: print gif url
      run: echo "GIF URL - ${{ steps.prComment.outputs.gif_url }}"
